import idaapi as api
import idc as idc
import json

# ask for the dumped file from dumper.py
path = api.ask_file(False, "*.json", "Input file, generated by dumper.py")

# read selection start
start = idc.read_selection_start()

# go back 8 bits until address has a name (Start of vtable usually has a "name" like off_123456, not accurate somtimes tho)
while not idc.get_name(start):
    start -=8

# dump dumper.py file into dict
d = {"Functions": {}}
with open(path, "r") as f:
    d = json.load(f)

# set vtable name to dumper.py symbol
idc.set_name(start, d.get("Name").get("Symbol"))
# loop through function dict values and apply symbol to each vtable entry
for func in d.get("Functions").values():
    idc.set_name(idc.get_qword(start), func, idc.SN_CHECK)
    # go to the next address
    start +=8

api.msg(f"\nPasted Vtable")